### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by Testato** [xcesco/argon-network-switcher#1]
Ciao Francesco,

I tried Argon on a Win7-64bit HP notebook, when i try to switch to some profile this error appear:

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Argon.Windows.RegistryUtility.WriteValue[T](RegistryKeyType type, String regKey, String name, T value, RegistryValueKind valueKind)
   at Argon.Windows7.Network.Win7NetworkCardManager.WriteDataIntoRegistry(WindowsNetworkCard card)
   at Argon.Windows.Network.WindowsNetworkCardManager.WriteDataIntoRegistry(WindowsNetworkCard card)
   at Argon.Windows7.Network.Win7NetworkCardManager.Apply(WindowsNetworkCard card)
   at Argon.Windows.Network.WindowsNetworkCardManager.Apply(WindowsNetworkCard card)
   at Argon.Windows.Network.Profile.NetworkProfile.Run(Boolean runDeviceConfig)
   at Argon.UseCase.UseCaseProfile.Run(NetworkProfile profile, BackgroundWorker worker, Boolean runDeviceConfig)
   at Argon.Windows.Forms.FormMain.backgroundWorker_DoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.36373 built by: FX452RTMLDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Argon
    Assembly Version: 1.4.9.0
    Win32 Version: 1.4.9.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Argon%20Network%20Switcher/Argon.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.36373 built by: FX452RTMLDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.36373 built by: FX452RTMLDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.36373 built by: FX452RTMLDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.36373 built by: FX452RTMLDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.36373 built by: FX452RTMLDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.36373 built by: FX452RTMLDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 2.7.0.0
    Win32 Version: 2.7.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Argon%20Network%20Switcher/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
System.Windows.Forms.Ribbon35
    Assembly Version: 3.5.5.0
    Win32 Version: 3.5.5.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Argon%20Network%20Switcher/System.Windows.Forms.Ribbon35.DLL
----------------------------------------
ArgonLibrary
    Assembly Version: 1.4.6.0
    Win32 Version: 1.4.6.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Argon%20Network%20Switcher/ArgonLibrary.DLL
----------------------------------------
ObjectListView
    Assembly Version: 2.8.0.22691
    Win32 Version: 2.8.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Argon%20Network%20Switcher/ObjectListView.DLL
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.36373 built by: FX452RTMLDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.36373 built by: FX452RTMLDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.36373 built by: FX452RTMLDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.36373
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.36373 built by: FX452RTMLDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.36373 built by: FX452RTMLDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------

```

**Comment by xcesco** [comment]
Tnx for the information, i will investigate about it
